FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock README.md ./
COPY orchestration ./orchestration
COPY dbt_project ./dbt_project

RUN uv sync --frozen

EXPOSE 3000

CMD ["sh", "-c", "uv run dbt parse --project-dir dbt_project && uv run dagster dev -h 0.0.0.0 -p 3000"]
